var annotated_dup =
[
    [ "ft", "namespaceft.html", [
      [ "irc", "namespaceft_1_1irc.html", [
        [ "bot", "classft_1_1irc_1_1bot.html", "classft_1_1irc_1_1bot" ],
        [ "bot_handler", "classft_1_1irc_1_1bot__handler.html", "classft_1_1irc_1_1bot__handler" ],
        [ "channel", "classft_1_1irc_1_1channel.html", "classft_1_1irc_1_1channel" ],
        [ "client_handler", "classft_1_1irc_1_1client__handler.html", "classft_1_1irc_1_1client__handler" ],
        [ "message", "classft_1_1irc_1_1message.html", "classft_1_1irc_1_1message" ],
        [ "message_decoder", "classft_1_1irc_1_1message__decoder.html", "classft_1_1irc_1_1message__decoder" ],
        [ "message_encoder", "classft_1_1irc_1_1message__encoder.html", "classft_1_1irc_1_1message__encoder" ],
        [ "processor_base", "classft_1_1irc_1_1processor__base.html", "classft_1_1irc_1_1processor__base" ],
        [ "processor_dictionary", "classft_1_1irc_1_1processor__dictionary.html", "classft_1_1irc_1_1processor__dictionary" ],
        [ "processor_join", "classft_1_1irc_1_1processor__join.html", "classft_1_1irc_1_1processor__join" ],
        [ "processor_part", "classft_1_1irc_1_1processor__part.html", "classft_1_1irc_1_1processor__part" ],
        [ "processor_mode", "classft_1_1irc_1_1processor__mode.html", "classft_1_1irc_1_1processor__mode" ],
        [ "processor_topic", "classft_1_1irc_1_1processor__topic.html", "classft_1_1irc_1_1processor__topic" ],
        [ "processor_names", "classft_1_1irc_1_1processor__names.html", "classft_1_1irc_1_1processor__names" ],
        [ "processor_list", "classft_1_1irc_1_1processor__list.html", "classft_1_1irc_1_1processor__list" ],
        [ "processor_invite", "classft_1_1irc_1_1processor__invite.html", "classft_1_1irc_1_1processor__invite" ],
        [ "processor_kick", "classft_1_1irc_1_1processor__kick.html", "classft_1_1irc_1_1processor__kick" ],
        [ "processor_ping", "classft_1_1irc_1_1processor__ping.html", "classft_1_1irc_1_1processor__ping" ],
        [ "processor_kill", "classft_1_1irc_1_1processor__kill.html", "classft_1_1irc_1_1processor__kill" ],
        [ "processor_away", "classft_1_1irc_1_1processor__away.html", "classft_1_1irc_1_1processor__away" ],
        [ "processor_cap", "classft_1_1irc_1_1processor__cap.html", "classft_1_1irc_1_1processor__cap" ],
        [ "processor_who", "classft_1_1irc_1_1processor__who.html", "classft_1_1irc_1_1processor__who" ],
        [ "processor_whois", "classft_1_1irc_1_1processor__whois.html", "classft_1_1irc_1_1processor__whois" ],
        [ "processor_pass", "classft_1_1irc_1_1processor__pass.html", "classft_1_1irc_1_1processor__pass" ],
        [ "processor_nick", "classft_1_1irc_1_1processor__nick.html", "classft_1_1irc_1_1processor__nick" ],
        [ "processor_user", "classft_1_1irc_1_1processor__user.html", "classft_1_1irc_1_1processor__user" ],
        [ "processor_oper", "classft_1_1irc_1_1processor__oper.html", "classft_1_1irc_1_1processor__oper" ],
        [ "processor_quit", "classft_1_1irc_1_1processor__quit.html", "classft_1_1irc_1_1processor__quit" ],
        [ "processor_message_base", "classft_1_1irc_1_1processor__message__base.html", "classft_1_1irc_1_1processor__message__base" ],
        [ "processor_privmsg", "classft_1_1irc_1_1processor__privmsg.html", "classft_1_1irc_1_1processor__privmsg" ],
        [ "processor_notice", "classft_1_1irc_1_1processor__notice.html", "classft_1_1irc_1_1processor__notice" ],
        [ "make_reply_base", "structft_1_1irc_1_1make__reply__base.html", "structft_1_1irc_1_1make__reply__base" ],
        [ "make_welcome", "structft_1_1irc_1_1make__welcome.html", "structft_1_1irc_1_1make__welcome" ],
        [ "make_error", "structft_1_1irc_1_1make__error.html", "structft_1_1irc_1_1make__error" ],
        [ "person_info", "structft_1_1irc_1_1person__info.html", "structft_1_1irc_1_1person__info" ],
        [ "channel_info", "structft_1_1irc_1_1channel__info.html", "structft_1_1irc_1_1channel__info" ],
        [ "member_info", "structft_1_1irc_1_1member__info.html", "structft_1_1irc_1_1member__info" ],
        [ "make_reply", "structft_1_1irc_1_1make__reply.html", "structft_1_1irc_1_1make__reply" ],
        [ "server", "classft_1_1irc_1_1server.html", "classft_1_1irc_1_1server" ],
        [ "server_handler", "classft_1_1irc_1_1server__handler.html", "classft_1_1irc_1_1server__handler" ],
        [ "string_line_decoder", "classft_1_1irc_1_1string__line__decoder.html", "classft_1_1irc_1_1string__line__decoder" ],
        [ "string_line_encoder", "classft_1_1irc_1_1string__line__encoder.html", "classft_1_1irc_1_1string__line__encoder" ],
        [ "string_utils", "structft_1_1irc_1_1string__utils.html", "structft_1_1irc_1_1string__utils" ],
        [ "user", "classft_1_1irc_1_1user.html", "classft_1_1irc_1_1user" ]
      ] ],
      [ "serv", "namespaceft_1_1serv.html", [
        [ "_internal", "namespaceft_1_1serv_1_1__internal.html", [
          [ "synchronized_helper", "classft_1_1serv_1_1__internal_1_1synchronized__helper.html", "classft_1_1serv_1_1__internal_1_1synchronized__helper" ],
          [ "ai_failed", "classft_1_1serv_1_1__internal_1_1ai__failed.html", "classft_1_1serv_1_1__internal_1_1ai__failed" ],
          [ "gai_guard", "structft_1_1serv_1_1__internal_1_1gai__guard.html", "structft_1_1serv_1_1__internal_1_1gai__guard" ],
          [ "forward_reference", "structft_1_1serv_1_1__internal_1_1forward__reference.html", "structft_1_1serv_1_1__internal_1_1forward__reference" ],
          [ "forward_reference< T & >", "structft_1_1serv_1_1__internal_1_1forward__reference_3_01T_01_6_01_4.html", "structft_1_1serv_1_1__internal_1_1forward__reference_3_01T_01_6_01_4" ],
          [ "forward_reference< const T & >", "structft_1_1serv_1_1__internal_1_1forward__reference_3_01const_01T_01_6_01_4.html", "structft_1_1serv_1_1__internal_1_1forward__reference_3_01const_01T_01_6_01_4" ],
          [ "forward_reference< volatile T & >", "structft_1_1serv_1_1__internal_1_1forward__reference_3_01volatile_01T_01_6_01_4.html", "structft_1_1serv_1_1__internal_1_1forward__reference_3_01volatile_01T_01_6_01_4" ],
          [ "forward_reference< const volatile T & >", "structft_1_1serv_1_1__internal_1_1forward__reference_3_01const_01volatile_01T_01_6_01_4.html", "structft_1_1serv_1_1__internal_1_1forward__reference_3_01const_01volatile_01T_01_6_01_4" ]
        ] ],
        [ "bootstrap", "classft_1_1serv_1_1bootstrap.html", "classft_1_1serv_1_1bootstrap" ],
        [ "byte_buffer", "classft_1_1serv_1_1byte__buffer.html", "classft_1_1serv_1_1byte__buffer" ],
        [ "bytes_decoder", "classft_1_1serv_1_1bytes__decoder.html", "classft_1_1serv_1_1bytes__decoder" ],
        [ "bytes_encoder", "classft_1_1serv_1_1bytes__encoder.html", "classft_1_1serv_1_1bytes__encoder" ],
        [ "event_channel_base", "classft_1_1serv_1_1event__channel__base.html", "classft_1_1serv_1_1event__channel__base" ],
        [ "event_handler_base", "classft_1_1serv_1_1event__handler__base.html", "classft_1_1serv_1_1event__handler__base" ],
        [ "event_layer", "classft_1_1serv_1_1event__layer.html", "classft_1_1serv_1_1event__layer" ],
        [ "event_worker", "classft_1_1serv_1_1event__worker.html", "classft_1_1serv_1_1event__worker" ],
        [ "event_worker_group", "classft_1_1serv_1_1event__worker__group.html", "classft_1_1serv_1_1event__worker__group" ],
        [ "file_channel", "classft_1_1serv_1_1file__channel.html", "classft_1_1serv_1_1file__channel" ],
        [ "logger", "structft_1_1serv_1_1logger.html", "structft_1_1serv_1_1logger" ],
        [ "logic_adapter", "classft_1_1serv_1_1logic__adapter.html", "classft_1_1serv_1_1logic__adapter" ],
        [ "object_decoder", "classft_1_1serv_1_1object__decoder.html", "classft_1_1serv_1_1object__decoder" ],
        [ "object_encoder", "classft_1_1serv_1_1object__encoder.html", "classft_1_1serv_1_1object__encoder" ],
        [ "errno_backup", "structft_1_1serv_1_1errno__backup.html", "structft_1_1serv_1_1errno__backup" ],
        [ "syscall_failed", "classft_1_1serv_1_1syscall__failed.html", "classft_1_1serv_1_1syscall__failed" ],
        [ "orderly_shutdown", "classft_1_1serv_1_1orderly__shutdown.html", "classft_1_1serv_1_1orderly__shutdown" ],
        [ "dynamic_array", "structft_1_1serv_1_1dynamic__array.html", "structft_1_1serv_1_1dynamic__array" ],
        [ "fast_dictionary", "structft_1_1serv_1_1fast__dictionary.html", "structft_1_1serv_1_1fast__dictionary" ],
        [ "dynamic_buffer", "structft_1_1serv_1_1dynamic__buffer.html", "structft_1_1serv_1_1dynamic__buffer" ],
        [ "unique_set", "structft_1_1serv_1_1unique__set.html", "structft_1_1serv_1_1unique__set" ],
        [ "server_channel", "classft_1_1serv_1_1server__channel.html", "classft_1_1serv_1_1server__channel" ],
        [ "socket_utils", "structft_1_1serv_1_1socket__utils.html", "structft_1_1serv_1_1socket__utils" ],
        [ "stream_channel", "classft_1_1serv_1_1stream__channel.html", "classft_1_1serv_1_1stream__channel" ],
        [ "task_base", "classft_1_1serv_1_1task__base.html", "classft_1_1serv_1_1task__base" ]
      ] ]
    ] ],
    [ "dummy_inbound_adapter", "classdummy__inbound__adapter.html", "classdummy__inbound__adapter" ],
    [ "dummy_outbound_adapter", "classdummy__outbound__adapter.html", "classdummy__outbound__adapter" ]
];