ft_irc: bot.cpp File Reference
bot.cpp File Reference
#include "irc_constants.hpp"
#include "message.hpp"
#include "message_decoder.hpp"
#include "message_encoder.hpp"
#include "reply.hpp"
#include "string_line_decoder.hpp"
#include "string_line_encoder.hpp"
#include "string_utils.hpp"
#include <libserv/libserv.hpp>
#include <smart_ptr/smart_ptr.hpp>
#include <unistd.h>
#include <cctype>
#include <csignal>
#include <cstdlib>
#include <sstream>
#include <string>
#include <vector>
Classes
class ft::irc::bot
class ft::irc::bot_handler
Namespaces
ft
ft::irc
Macros
#define FT_IRC_ADD_ALL_SUPPORT_PARAM(_ADD)
Functions
static ft::shared_ptr< ft::serv::event_channel_base > ft::irc::_make_client (ft::serv::ident_t ident, const std::string &host, int serv, void *arg)
static void _on_signal (int signo)
int main (int argc, char *argv[])
Variables
ft::shared_ptr< ft::serv::event_worker_group > child_group
Macro Definition Documentation
FT_IRC_ADD_ALL_SUPPORT_PARAM
#define FT_IRC_ADD_ALL_SUPPORT_PARAM (_ADD)
Value:
    _ADD("AWAYLEN=" XSTR(FT_IRC_AWAYLEN));       \
    _ADD("CASEMAPPING=" FT_IRC_CASEMAPPING);     \
    _ADD("CHANLIMIT=" FT_IRC_CHANLIMIT);         \
    _ADD("CHANMODES=" FT_IRC_CHANMODES);         \
    _ADD("CHANNELLEN=" XSTR(FT_IRC_CHANNELLEN)); \
    _ADD("CHANTYPES=" FT_IRC_CHANTYPES);         \
    _ADD("HOSTLEN=" XSTR(FT_IRC_HOSTLEN));       \
    _ADD("KICKLEN=" XSTR(FT_IRC_KICKLEN));       \
    _ADD("MAXLIST=" FT_IRC_MAXLIST);             \
    _ADD("MAXTARGETS=" XSTR(FT_IRC_MAXTARGETS)); \
    _ADD("MODES=" XSTR(FT_IRC_MODES));           \
    _ADD("NETWORK=" FT_IRC_NETWORK);             \
    _ADD("NICKLEN=" XSTR(FT_IRC_NICKLEN));       \
    _ADD("PREFIX=" FT_IRC_PREFIX);               \
    _ADD("STATUSMSG=" FT_IRC_STATUSMSG);         \
    _ADD("TOPICLEN=" XSTR(FT_IRC_TOPICLEN));     \
    _ADD("USERLEN=" XSTR(FT_IRC_USERLEN));\
Function Documentation
_on_signal()
static void _on_signal (int signo) static
References child_group.
main()
int main (int argc, char * argv[])
References ft::irc::_make_client(), _on_signal(), child_group, ft::serv::logger::error(), ft::serv::bootstrap::set_success(), ft::serv::bootstrap::start_client(), ft::serv::logger::warn(), and ft::serv::syscall_failed::what().
Variable Documentation
child_group
ft::shared_ptr<ft::serv::event_worker_group> child_group