ft_irc: ft::irc::message Class Reference
ft::irc::message Class Reference
#include <message.hpp>
Public Types
typedef ft::serv::dynamic_array< std::string >::type param_vector
Public Member Functions
message ()
message (int command)
message (const std::string &command)
message (const std::string &prefix, const std::string &command, const param_vector &params)
message (const message &that)
message & operator= (const message &that)
std::string & operator[] (param_vector::size_type n)
const std::string & operator[] (param_vector::size_type n) const
message & operator>> (const std::string &prefix)
message & operator<< (const std::string &str)
template<typename T >
message & operator<< (const T &obj)
const std::string & get_command () const
const std::string & get_prefix () const
void set_prefix (const std::string &prefix)
std::size_t param_size () const
void add_param (const std::string &param)
std::string to_string () const
std::string to_pretty_string () const
Static Public Member Functions
static param_vector split (const std::string &str, std::string::value_type delim=' ', std::string::value_type limit='\0')
static bool try_parse (const std::string &str, message &out_msg)
Private Attributes
std::string command
std::string prefix
param_vector params
Member Typedef Documentation
param_vector
typedef ft::serv::dynamic_array<std::string>::type ft::irc::message::param_vector
Constructor & Destructor Documentation
message() [1/5]
ft::irc::message::message ()
message() [2/5]
ft::irc::message::message (int command)
References _validate_command(), and command.
message() [3/5]
ft::irc::message::message (const std::string & command)
References _validate_command().
message() [4/5]
ft::irc::message::message (const std::string & prefix, const std::string & command, const param_vector & params)
References _validate_command().
message() [5/5]
ft::irc::message::message (const message & that)
Member Function Documentation
add_param()
void ft::irc::message::add_param (const std::string & param)
get_command()
const std::string & ft::irc::message::get_command () const
get_prefix()
const std::string & ft::irc::message::get_prefix () const
operator<<() [1/2]
ft::irc::message & ft::irc::message::operator<< (const std::string & str)
operator<<() [2/2]
template<typename T > message& ft::irc::message::operator<< (const T & obj)
operator=()
ft::irc::message & ft::irc::message::operator= (const message & that)
References command, params, and prefix.
operator>>()
ft::irc::message & ft::irc::message::operator>> (const std::string & prefix)
operator[]() [1/2]
std::string & ft::irc::message::operator[] (param_vector::size_type n)
operator[]() [2/2]
const std::string & ft::irc::message::operator[] (param_vector::size_type n) const
param_size()
std::size_t ft::irc::message::param_size () const
set_prefix()
void ft::irc::message::set_prefix (const std::string & prefix)
split()
ft::irc::message::param_vector ft::irc::message::split (const std::string & str, std::string::value_type delim = ' ', std::string::value_type limit = '\0') static
to_pretty_string()
std::string ft::irc::message::to_pretty_string () const
to_string()
std::string ft::irc::message::to_string () const
try_parse()
bool ft::irc::message::try_parse (const std::string & str, message & out_msg) static
References _validate_command(), FT_IRC_MESSAGE_PARAM_LIMIT, and split().
Member Data Documentation
command
std::string ft::irc::message::command private
params
param_vector ft::irc::message::params private
prefix
std::string ft::irc::message::prefix private
The documentation for this class was generated from the following files:
message.hpp
message.cpp