ft_irc: ft::irc::server Class Reference
ft::irc::server Class Reference
#include <server.hpp>
Public Types
typedef ft::serv::fast_dictionary< std::string, ft::shared_ptr< ft::irc::channel > >::type channel_dictionary
typedef ft::serv::unique_set< std::string >::type nick_set
typedef ft::serv::dynamic_array< ft::shared_ptr< ft::irc::user > >::type user_list
Public Member Functions
server (const std::string &pass)
~server ()
std::string make_full_name () const throw ()
std::vector< std::string > make_motd_lines () const throw ()
std::vector< std::string > make_support_params () const throw ()
const std::string & get_pass () const throw ()
ft::shared_ptr< ft::irc::channel > find_channel (const std::string &name) const throw ()
ft::shared_ptr< ft::irc::channel > ensure_channel (const std::string &name)
void remove_channel (const std::string &name)
bool hold_nick (const std::string &nick)
void release_nick (const std::string &nick) throw ()
ft::shared_ptr< ft::irc::user > find_user (const std::string &name) const throw ()
void register_user (const ft::shared_ptr< ft::irc::user > &user)
void deregister_user (const ft::shared_ptr< ft::irc::user > &user)
void send_welcome (const ft::irc::user &user) const throw ()
void send_list (const ft::irc::user &user, const ft::irc::message::param_vector &query) const throw ()
void broadcast_all (const ft::irc::message &message, ft::shared_ptr< const ft::irc::user > except=ft::shared_ptr< ft::irc::user >()) const
ft::irc::reply_numerics check_signature (const std::string &user, const std::string &pass) const
Private Member Functions
server (const server &)
server & operator= (const server &)
Private Attributes
std::string pass
channel_dictionary channels
nick_set nicks
user_list users
ft::readwrite_lock lock
std::string created_time
Member Typedef Documentation
channel_dictionary
typedef ft::serv::fast_dictionary<std::string, ft::shared_ptr<ft::irc::channel> >::type ft::irc::server::channel_dictionary
nick_set
typedef ft::serv::unique_set<std::string>::type ft::irc::server::nick_set
user_list
typedef ft::serv::dynamic_array<ft::shared_ptr<ft::irc::user> >::type ft::irc::server::user_list
Constructor & Destructor Documentation
server() [1/2]
ft::irc::server::server (const std::string & pass)
~server()
ft::irc::server::~server ()
server() [2/2]
ft::irc::server::server (const server &) private
Member Function Documentation
broadcast_all()
void ft::irc::server::broadcast_all (const ft::irc::message & message, ft::shared_ptr< const ft::irc::user > except = ft::shared_ptr<ft::irc::user>()) const
References ft::irc::user::send_message().
check_signature()
ft::irc::reply_numerics ft::irc::server::check_signature (const std::string & user, const std::string & pass) const
References FT_IRC_OPERATOR_NAME, and FT_IRC_OPERATOR_PASS.
deregister_user()
void ft::irc::server::deregister_user (const ft::shared_ptr< ft::irc::user > & user)
ensure_channel()
ft::shared_ptr< ft::irc::channel > ft::irc::server::ensure_channel (const std::string & name)
find_channel()
ft::shared_ptr< ft::irc::channel > ft::irc::server::find_channel (const std::string & name) const throw ()
find_user()
ft::shared_ptr< ft::irc::user > ft::irc::server::find_user (const std::string & name) const throw ()
get_pass()
const std::string & ft::irc::server::get_pass () const throw ()
hold_nick()
bool ft::irc::server::hold_nick (const std::string & nick)
References ft::irc::string_utils::to_lower().
make_full_name()
std::string ft::irc::server::make_full_name () const throw ()
References FT_IRC_SERVER_NAME.
make_motd_lines()
std::vector< std::string > ft::irc::server::make_motd_lines () const throw ()
References FT_IRC_ADD_ALL_MOTD.
make_support_params()
std::vector< std::string > ft::irc::server::make_support_params () const throw ()
References FT_IRC_ADD_ALL_SUPPORT_PARAM.
operator=()
server& ft::irc::server::operator= (const server &) private
register_user()
void ft::irc::server::register_user (const ft::shared_ptr< ft::irc::user > & user)
release_nick()
void ft::irc::server::release_nick (const std::string & nick) throw ()
References ft::irc::string_utils::to_lower().
remove_channel()
void ft::irc::server::remove_channel (const std::string & name)
send_list()
void ft::irc::server::send_list (const ft::irc::user & user, const ft::irc::message::param_vector & query) const throw ()
References ft::irc::channel::CHANNEL_MODE_PRIVATE, ft::irc::channel::CHANNEL_MODE_SECRET, ft::irc::channel::get_name(), ft::irc::user::is_channel_member(), ft::irc::make_reply::list_end(), ft::irc::make_reply::list_start(), ft::irc::channel::load_mode(), ft::irc::user::load_mode(), ft::irc::channel::make_list_packet(), ft::irc::user::send_message(), and ft::irc::user::USER_MODE_OPERATOR.
send_welcome()
void ft::irc::server::send_welcome (const ft::irc::user & user) const throw ()
References ft::irc::make_welcome::created(), ft::irc::make_reply::end_of_motd(), FT_IRC_CMODES, FT_IRC_NETWORK, FT_IRC_UMODES, FT_IRC_VERSION, ft::irc::make_welcome::i_support(), ft::irc::make_reply::luser_channels(), ft::irc::make_reply::luser_client(), ft::irc::make_reply::luser_me(), ft::irc::make_reply::luser_operator(), ft::irc::make_reply::luser_unknown(), ft::irc::user::make_full_name(), ft::irc::make_reply::motd(), ft::irc::make_reply::motd_start(), ft::irc::make_welcome::my_info(), ft::irc::make_error::no_motd(), ft::irc::user::send_message(), ft::irc::user::USER_MODE_INVISIBLE, ft::irc::user::USER_MODE_OPERATOR, ft::irc::make_welcome::welcome(), and ft::irc::make_welcome::your_host().
Member Data Documentation
channels
channel_dictionary ft::irc::server::channels private
created_time
std::string ft::irc::server::created_time private
lock
ft::readwrite_lock ft::irc::server::lock mutable private
nicks
nick_set ft::irc::server::nicks private
pass
std::string ft::irc::server::pass private
users
user_list ft::irc::server::users private
The documentation for this class was generated from the following files:
server.hpp
server.cpp