ft_irc: ft::irc::user Class Reference
ft::irc::user Class Reference
#include <user.hpp>
Classes
struct pred_equals_nick
Public Types
enum user_mode { USER_MODE_OPERATOR , USER_MODE_INVISIBLE , USER_MODE_AWAY , NUMBEROF_USER_MODE }
enum register_state {
REGISTER_STATE_PASS , REGISTER_STATE_NICK , REGISTER_STATE_USER , REGISTER_STATE_COMPLETED ,
NUMBEROF_REGISTER_STATE
}
typedef ft::serv::dynamic_array< std::string >::type channel_list
typedef ft::serv::dynamic_array< ft::shared_ptr< channel >::element_type * >::type invite_list
Public Member Functions
user (ft::irc::server &server, const ft::shared_ptr< ft::serv::event_layer > &layer)
~user ()
ft::irc::server & get_server () const throw ()
const std::string & get_nick () const throw ()
void set_nick (const std::string &nick)
std::string load_nick () const
bool change_nick (const std::string &nick)
const std::string & get_username () const throw ()
void set_username (const std::string &username)
const std::string & get_hostname () const throw ()
std::string make_full_name () const throw ()
const std::string & get_realname () const throw ()
void set_realname (const std::string &realname)
bool get_mode (user_mode index) const throw ()
void set_mode (user_mode index, bool value) throw ()
bool load_mode (user_mode index) const throw ()
void store_mode (user_mode index, bool value) throw ()
std::string make_mode_string ()
bool get_register_state (register_state index) const throw ()
void set_register_state (register_state index, bool value) throw ()
bool is_registered () const throw ()
void register_to_server ()
void deregister_from_server ()
const std::string & get_away_message () const throw ()
void set_away_message (const std::string &away_message)
std::string load_away_message () const
void store_away_message (const std::string &away_message)
void reset_away_message () throw ()
const std::string & get_quit_message () const throw ()
void set_quit_message (const std::string &quit_message)
std::string load_quit_message () const
void store_quit_message (const std::string &quit_message)
void reset_quit_message () throw ()
channel_list channel_names_snapshot () const throw ()
channel_list::size_type channel_count () const throw ()
bool is_channel_member (const std::string &channelname) const throw ()
void join_channel (const std::string &channelname)
void part_channel (const std::string &channelname)
bool contains_invite (const ft::shared_ptr< channel > &channel) const
void add_invite (const ft::shared_ptr< channel > &channel)
void remove_invite (const ft::shared_ptr< channel > &channel)
void send_message (const ft::irc::message &message) const
void notify_message (const ft::irc::message &message) const
void exit_client () const
Private Member Functions
user (const user &)
user & operator= (const user &)
Private Attributes
ft::irc::server & server
ft::weak_ptr< ft::serv::event_layer > layer
std::string nick
std::string username
std::string hostname
std::string realname
channel_list channels
invite_list invites
std::bitset< NUMBEROF_USER_MODE > mode
std::bitset< NUMBEROF_REGISTER_STATE > registered_state
std::string away_message
std::string quit_message
ft::readwrite_lock lock
Member Typedef Documentation
channel_list
typedef ft::serv::dynamic_array<std::string>::type ft::irc::user::channel_list
invite_list
typedef ft::serv::dynamic_array<ft::shared_ptr<channel>::element_type*>::type ft::irc::user::invite_list
Member Enumeration Documentation
register_state
enum ft::irc::user::register_state
Enumerator
REGISTER_STATE_PASS
REGISTER_STATE_NICK
REGISTER_STATE_USER
REGISTER_STATE_COMPLETED
NUMBEROF_REGISTER_STATE
user_mode
enum ft::irc::user::user_mode
Enumerator
USER_MODE_OPERATOR
USER_MODE_INVISIBLE
USER_MODE_AWAY
NUMBEROF_USER_MODE
Constructor & Destructor Documentation
user() [1/2]
ft::irc::user::user (ft::irc::server & server, const ft::shared_ptr< ft::serv::event_layer > & layer)
References channels, and FT_IRC_CHANNEL_LIMIT_PER_USER.
~user()
ft::irc::user::~user ()
user() [2/2]
ft::irc::user::user (const user &) private
Member Function Documentation
add_invite()
void ft::irc::user::add_invite (const ft::shared_ptr< channel > & channel)
change_nick()
bool ft::irc::user::change_nick (const std::string & nick)
References ft::irc::server::hold_nick(), ft::irc::server::release_nick(), ft::irc::make_reply_base::set_user_nick(), and ft::irc::string_utils::to_lower().
channel_count()
ft::irc::user::channel_list::size_type ft::irc::user::channel_count () const throw ()
channel_names_snapshot()
ft::irc::user::channel_list ft::irc::user::channel_names_snapshot () const throw ()
contains_invite()
bool ft::irc::user::contains_invite (const ft::shared_ptr< channel > & channel) const
deregister_from_server()
void ft::irc::user::deregister_from_server ()
References ft::irc::server::deregister_user(), ft::irc::server::find_channel(), ft::irc::channel::leave_user(), REGISTER_STATE_COMPLETED, REGISTER_STATE_NICK, and ft::irc::server::release_nick().
exit_client()
void ft::irc::user::exit_client () const
get_away_message()
const std::string & ft::irc::user::get_away_message () const throw ()
get_hostname()
const std::string & ft::irc::user::get_hostname () const throw ()
get_mode()
bool ft::irc::user::get_mode (user_mode index) const throw ()
get_nick()
const std::string & ft::irc::user::get_nick () const throw ()
get_quit_message()
const std::string & ft::irc::user::get_quit_message () const throw ()
get_realname()
const std::string & ft::irc::user::get_realname () const throw ()
get_register_state()
bool ft::irc::user::get_register_state (register_state index) const throw ()
get_server()
ft::irc::server & ft::irc::user::get_server () const throw ()
get_username()
const std::string & ft::irc::user::get_username () const throw ()
is_channel_member()
bool ft::irc::user::is_channel_member (const std::string & channelname) const throw ()
is_registered()
bool ft::irc::user::is_registered () const throw ()
join_channel()
void ft::irc::user::join_channel (const std::string & channelname)
load_away_message()
std::string ft::irc::user::load_away_message () const
load_mode()
bool ft::irc::user::load_mode (user_mode index) const throw ()
load_nick()
std::string ft::irc::user::load_nick () const
load_quit_message()
std::string ft::irc::user::load_quit_message () const
make_full_name()
std::string ft::irc::user::make_full_name () const throw ()
make_mode_string()
std::string ft::irc::user::make_mode_string ()
notify_message()
void ft::irc::user::notify_message (const ft::irc::message & message) const
References ft::irc::channel::broadcast_unique(), and ft::irc::server::find_channel().
operator=()
user& ft::irc::user::operator= (const user &) private
part_channel()
void ft::irc::user::part_channel (const std::string & channelname)
register_to_server()
void ft::irc::user::register_to_server ()
References REGISTER_STATE_COMPLETED, ft::irc::server::register_user(), ft::irc::server::send_welcome(), and ft::irc::make_reply::user_mode_is().
remove_invite()
void ft::irc::user::remove_invite (const ft::shared_ptr< channel > & channel)
reset_away_message()
void ft::irc::user::reset_away_message () throw ()
reset_quit_message()
void ft::irc::user::reset_quit_message () throw ()
send_message()
void ft::irc::user::send_message (const ft::irc::message & message) const
References ft::serv::logger::debug(), and ft::irc::message::to_pretty_string().
set_away_message()
void ft::irc::user::set_away_message (const std::string & away_message)
set_mode()
void ft::irc::user::set_mode (user_mode index, bool value) throw ()
set_nick()
void ft::irc::user::set_nick (const std::string & nick)
set_quit_message()
void ft::irc::user::set_quit_message (const std::string & quit_message)
set_realname()
void ft::irc::user::set_realname (const std::string & realname)
set_register_state()
void ft::irc::user::set_register_state (register_state index, bool value) throw ()
set_username()
void ft::irc::user::set_username (const std::string & username)
store_away_message()
void ft::irc::user::store_away_message (const std::string & away_message)
store_mode()
void ft::irc::user::store_mode (user_mode index, bool value) throw ()
store_quit_message()
void ft::irc::user::store_quit_message (const std::string & quit_message)
Member Data Documentation
away_message
std::string ft::irc::user::away_message private
channels
channel_list ft::irc::user::channels private
hostname
std::string ft::irc::user::hostname private
invites
invite_list ft::irc::user::invites private
layer
ft::weak_ptr<ft::serv::event_layer> ft::irc::user::layer private
lock
ft::readwrite_lock ft::irc::user::lock mutable private
mode
std::bitset<NUMBEROF_USER_MODE> ft::irc::user::mode private
nick
std::string ft::irc::user::nick private
quit_message
std::string ft::irc::user::quit_message private
realname
std::string ft::irc::user::realname private
registered_state
std::bitset<NUMBEROF_REGISTER_STATE> ft::irc::user::registered_state private
server
ft::irc::server& ft::irc::user::server private
username
std::string ft::irc::user::username private
The documentation for this class was generated from the following files:
user.hpp
user.cpp