ft_irc: ft::irc::bot Class Reference
ft::irc::bot Class Reference
Public Types
typedef ft::serv::fast_dictionary< std::string, std::string >::type owner_dictionary
typedef ft::serv::fast_dictionary< std::string, std::vector< std::string > >::type names_dictionary
Public Member Functions
bot (const std::string &pass, const std::string &nick, const std::string &username, const std::string &realname, const std::string &path)
~bot ()
const std::string & get_pass () const throw ()
const std::string & get_nick () const throw ()
const std::string & get_username () const throw ()
const std::string & get_hostname () const throw ()
const std::string & get_servername () const throw ()
const std::string & get_realname () const throw ()
const std::string & get_owner (const std::string &channel) const throw ()
void set_owner (const std::string &channel, const std::string &owner_nick)
bool is_owner (const std::string &channel, const std::string &nick) const
void leave_channel (const std::string &channel) throw ()
std::vector< std::string > find_own_channels (const std::string &owner_nick)
void update_nick (const std::string &old_nick, const std::string &new_nick)
void send_auth (ft::serv::event_layer &layer) const
void send_packet (ft::serv::event_layer &layer, const ft::irc::message &msg) const
void on_privmsg (ft::serv::event_layer &layer, ft::irc::message &message)
void on_invite (ft::serv::event_layer &layer, ft::irc::message &message)
void on_kick (ft::serv::event_layer &layer, ft::irc::message &message)
void on_part (ft::serv::event_layer &layer, ft::irc::message &message)
void on_quit (ft::serv::event_layer &layer, ft::irc::message &message)
void on_nick (ft::serv::event_layer &layer, ft::irc::message &message)
void on_name_reply (ft::serv::event_layer &layer, ft::irc::message &message)
void on_end_of_names (ft::serv::event_layer &layer, ft::irc::message &message)
void on_bad_error (ft::serv::event_layer &layer, ft::irc::message &message)
void on_nick_error (ft::serv::event_layer &layer, ft::irc::message &message)
void on_packet (ft::serv::event_layer &layer, ft::irc::message &message)
Private Member Functions
bot (const bot &)
bot & operator= (const bot &)
Private Attributes
std::string pass
std::string nick
std::string username
std::string hostname
std::string servername
std::string realname
std::string path
owner_dictionary channel_owners
names_dictionary names_map
Member Typedef Documentation
names_dictionary
typedef ft::serv::fast_dictionary<std::string, std::vector<std::string> >::type ft::irc::bot::names_dictionary
owner_dictionary
typedef ft::serv::fast_dictionary<std::string, std::string>::type ft::irc::bot::owner_dictionary
Constructor & Destructor Documentation
bot() [1/2]
ft::irc::bot::bot (const std::string & pass, const std::string & nick, const std::string & username, const std::string & realname, const std::string & path) inline
~bot()
ft::irc::bot::~bot () inline
bot() [2/2]
ft::irc::bot::bot (const bot &) private
Member Function Documentation
find_own_channels()
std::vector<std::string> ft::irc::bot::find_own_channels (const std::string & owner_nick) inline
References ft::irc::string_utils::is_same().
get_hostname()
const std::string& ft::irc::bot::get_hostname () const throw () inline
References hostname.
get_nick()
const std::string& ft::irc::bot::get_nick () const throw () inline
References nick.
get_owner()
const std::string& ft::irc::bot::get_owner (const std::string & channel) const throw () inline
get_pass()
const std::string& ft::irc::bot::get_pass () const throw () inline
References pass.
get_realname()
const std::string& ft::irc::bot::get_realname () const throw () inline
References realname.
get_servername()
const std::string& ft::irc::bot::get_servername () const throw () inline
References servername.
get_username()
const std::string& ft::irc::bot::get_username () const throw () inline
References username.
is_owner()
bool ft::irc::bot::is_owner (const std::string & channel, const std::string & nick) const inline
References get_owner(), ft::irc::string_utils::is_same(), and nick.
leave_channel()
void ft::irc::bot::leave_channel (const std::string & channel) throw () inline
on_bad_error()
void ft::irc::bot::on_bad_error (ft::serv::event_layer & layer, ft::irc::message & message) inline
References get_owner(), and send_packet().
on_end_of_names()
void ft::irc::bot::on_end_of_names (ft::serv::event_layer & layer, ft::irc::message & message) inline
References send_packet().
on_invite()
void ft::irc::bot::on_invite (ft::serv::event_layer & layer, ft::irc::message & message) inline
References ft::irc::message::get_prefix(), ft::irc::string_utils::pick_nick(), send_packet(), and set_owner().
on_kick()
void ft::irc::bot::on_kick (ft::serv::event_layer & layer, ft::irc::message & message) inline
References get_nick(), is_owner(), ft::irc::string_utils::is_same(), leave_channel(), and send_packet().
on_name_reply()
void ft::irc::bot::on_name_reply (ft::serv::event_layer & layer, ft::irc::message & message) inline
References nick, and ft::irc::message::split().
on_nick()
void ft::irc::bot::on_nick (ft::serv::event_layer & layer, ft::irc::message & message) inline
References ft::irc::message::get_prefix(), ft::irc::string_utils::pick_nick(), and update_nick().
on_nick_error()
void ft::irc::bot::on_nick_error (ft::serv::event_layer & layer, ft::irc::message & message) inline
References ft::serv::event_layer::post_disconnect().
on_packet()
void ft::irc::bot::on_packet (ft::serv::event_layer & layer, ft::irc::message & message) inline
References ft::irc::message::get_command(), on_bad_error(), on_end_of_names(), on_invite(), on_kick(), on_name_reply(), on_nick(), on_nick_error(), on_part(), on_privmsg(), and on_quit().
on_part()
void ft::irc::bot::on_part (ft::serv::event_layer & layer, ft::irc::message & message) inline
References ft::irc::message::get_prefix(), is_owner(), leave_channel(), ft::irc::string_utils::pick_nick(), and send_packet().
on_privmsg()
void ft::irc::bot::on_privmsg (ft::serv::event_layer & layer, ft::irc::message & message) inline
References FT_IRC_MESSAGE_LINE_LIMIT, ft::irc::message::get_prefix(), ft::irc::string_utils::is_valid_channelname(), ft::irc::string_utils::pick_nick(), and send_packet().
on_quit()
void ft::irc::bot::on_quit (ft::serv::event_layer & layer, ft::irc::message & message) inline
References find_own_channels(), ft::irc::message::get_prefix(), leave_channel(), ft::irc::string_utils::pick_nick(), and send_packet().
operator=()
bot& ft::irc::bot::operator= (const bot &) private
send_auth()
void ft::irc::bot::send_auth (ft::serv::event_layer & layer) const inline
References get_hostname(), get_nick(), get_pass(), get_realname(), get_servername(), get_username(), ft::serv::event_layer::post_flush(), and ft::serv::event_layer::post_write().
send_packet()
void ft::irc::bot::send_packet (ft::serv::event_layer & layer, const ft::irc::message & msg) const inline
References ft::serv::event_layer::post_flush(), and ft::serv::event_layer::post_write().
set_owner()
void ft::irc::bot::set_owner (const std::string & channel, const std::string & owner_nick) inline
update_nick()
void ft::irc::bot::update_nick (const std::string & old_nick, const std::string & new_nick) inline
References ft::irc::string_utils::is_same().
Member Data Documentation
channel_owners
owner_dictionary ft::irc::bot::channel_owners private
hostname
std::string ft::irc::bot::hostname private
names_map
names_dictionary ft::irc::bot::names_map private
nick
std::string ft::irc::bot::nick private
pass
std::string ft::irc::bot::pass private
path
std::string ft::irc::bot::path private
realname
std::string ft::irc::bot::realname private
servername
std::string ft::irc::bot::servername private
username
std::string ft::irc::bot::username private
The documentation for this class was generated from the following file:
bot.cpp