ft_irc: dummy_inbound_adapter Class Reference
dummy_inbound_adapter Class Reference
Public Member Functions
dummy_inbound_adapter (ft::serv::event_channel_base &channel)
~dummy_inbound_adapter ()
void on_register (ft::serv::event_layer &layer)
void on_write (ft::serv::event_layer &layer, ft::shared_ptr< const void > arg)
void on_flush (ft::serv::event_layer &layer)
void on_finish (ft::serv::event_layer &layer)
void on_disconnect (ft::serv::event_layer &layer)
Public Member Functions inherited from ft::serv::event_handler_base
event_handler_base ()
virtual ~event_handler_base ()
virtual void on_active (event_layer &layer)
virtual void on_read (event_layer &layer, ft::shared_ptr< void >)
virtual void on_read_complete (event_layer &layer)
virtual void on_error (event_layer &layer, ft::shared_ptr< const std::exception >)
virtual void on_inactive (event_layer &layer)
Private Member Functions
dummy_inbound_adapter (const dummy_inbound_adapter &)
dummy_inbound_adapter & operator= (const dummy_inbound_adapter &)
Private Attributes
ft::serv::event_channel_base & channel
Constructor & Destructor Documentation
dummy_inbound_adapter() [1/2]
dummy_inbound_adapter::dummy_inbound_adapter (ft::serv::event_channel_base & channel) inline
~dummy_inbound_adapter()
dummy_inbound_adapter::~dummy_inbound_adapter () inline
dummy_inbound_adapter() [2/2]
dummy_inbound_adapter::dummy_inbound_adapter (const dummy_inbound_adapter &) private
Member Function Documentation
on_disconnect()
void dummy_inbound_adapter::on_disconnect (ft::serv::event_layer & layer) inline virtual
Reimplemented from ft::serv::event_handler_base.
References ft::serv::event_channel_base::shutdown_input(), and ft::serv::event_channel_base::shutdown_output().
on_finish()
void dummy_inbound_adapter::on_finish (ft::serv::event_layer & layer) inline virtual
Reimplemented from ft::serv::event_handler_base.
References ft::serv::event_channel_base::finish().
on_flush()
void dummy_inbound_adapter::on_flush (ft::serv::event_layer & layer) inline virtual
Reimplemented from ft::serv::event_handler_base.
References ft::serv::event_channel_base::flush().
on_register()
void dummy_inbound_adapter::on_register (ft::serv::event_layer & layer) inline virtual
Reimplemented from ft::serv::event_handler_base.
References ft::serv::event_channel_base::get_loop(), and ft::serv::event_channel_base::get_pipeline().
on_write()
void dummy_inbound_adapter::on_write (ft::serv::event_layer & layer, ft::shared_ptr< const void > arg) inline virtual
Reimplemented from ft::serv::event_handler_base.
References ft::serv::event_channel_base::write().
operator=()
dummy_inbound_adapter& dummy_inbound_adapter::operator= (const dummy_inbound_adapter &) private
Member Data Documentation
channel
ft::serv::event_channel_base& dummy_inbound_adapter::channel private
The documentation for this class was generated from the following file:
includes/libserv/event_channel_base.cpp