ft_irc: ft::irc::channel Class Reference
ft::irc::channel Class Reference
#include <channel.hpp>
Classes
struct ban_info
struct member
Public Types
enum channel_mode {
CHANNEL_MODE_PRIVATE , CHANNEL_MODE_SECRET , CHANNEL_MODE_MODERATED , CHANNEL_MODE_TOPIC_LIMIT ,
CHANNEL_MODE_INVITE_ONLY , CHANNEL_MODE_NO_PRIVMSG , CHANNEL_MODE_KEY , CHANNEL_MODE_LIMIT ,
NUMBEROF_CHANNEL_MODE
}
typedef ft::serv::dynamic_array< member >::type member_list
typedef ft::serv::dynamic_array< ban_info >::type ban_list
Public Member Functions
channel (ft::irc::server &server, const std::string &pass)
~channel ()
const std::string & get_name () const throw ()
const std::string & get_topic () const throw ()
void set_topic (const std::string &topic)
std::string load_topic () const
void store_topic (const std::string &topic)
bool get_mode (channel_mode index) const throw ()
void set_mode (channel_mode index, bool value) throw ()
bool load_mode (channel_mode index) const throw ()
void store_mode (channel_mode index, bool value) throw ()
std::string make_mode_string (std::string *param)
std::size_t get_limit () const throw ()
void set_limit (std::size_t limit) throw ()
std::size_t load_limit () const throw ()
void store_limit (std::size_t limit) throw ()
const std::string & get_key () const throw ()
void set_key (const std::string &key)
std::string load_key () const
void store_key (const std::string &key)
ft::irc::reply_numerics enter_user (ft::irc::user &user, const std::string &key)
void leave_user (const ft::irc::user &user)
void send_names (const ft::irc::user &user) const
ft::irc::message make_list_packet (bool force) const
void send_ban_list (const ft::irc::user &user) const
void broadcast (const ft::irc::message &message, const ft::irc::user *except=null) const
void broadcast_unique (const ft::irc::message &message, ft::serv::unique_set< ft::shared_ptr< const ft::irc::user > >::type &unique_set) const
bool is_channel_operator (const ft::irc::user &user) const throw ()
bool is_channel_speaker (const ft::irc::user &user) const throw ()
void modify_member_mode (const std::string &nick, member::member_mode index, bool value) throw ()
bool is_banned (const ft::irc::user &user) const
void ban (const std::string &mask)
void unban (const std::string &mask)
Private Member Functions
channel (const channel &)
channel & operator= (const channel &)
Private Attributes
ft::irc::server & server
std::string name
std::string topic
std::bitset< NUMBEROF_CHANNEL_MODE > mode
std::size_t limit
std::string key
member_list members
ban_list bans
ft::readwrite_lock lock
bool invalidated
Member Typedef Documentation
ban_list
typedef ft::serv::dynamic_array<ban_info>::type ft::irc::channel::ban_list
member_list
typedef ft::serv::dynamic_array<member>::type ft::irc::channel::member_list
Member Enumeration Documentation
channel_mode
enum ft::irc::channel::channel_mode
Enumerator
CHANNEL_MODE_PRIVATE
CHANNEL_MODE_SECRET
CHANNEL_MODE_MODERATED
CHANNEL_MODE_TOPIC_LIMIT
CHANNEL_MODE_INVITE_ONLY
CHANNEL_MODE_NO_PRIVMSG
CHANNEL_MODE_KEY
CHANNEL_MODE_LIMIT
NUMBEROF_CHANNEL_MODE
Constructor & Destructor Documentation
channel() [1/2]
ft::irc::channel::channel (ft::irc::server & server, const std::string & pass)
~channel()
ft::irc::channel::~channel ()
channel() [2/2]
ft::irc::channel::channel (const channel &) private
Member Function Documentation
ban()
void ft::irc::channel::ban (const std::string & mask)
References ft::irc::channel::ban_info::host, ft::irc::string_utils::is_same(), ft::irc::channel::ban_info::name, ft::irc::string_utils::pick_host(), ft::irc::string_utils::pick_nick(), ft::irc::string_utils::pick_username(), and ft::irc::channel::ban_info::username.
broadcast()
void ft::irc::channel::broadcast (const ft::irc::message & message, const ft::irc::user * except = null) const
broadcast_unique()
void ft::irc::channel::broadcast_unique (const ft::irc::message & message, ft::serv::unique_set< ft::shared_ptr< const ft::irc::user > >::type & unique_set) const
enter_user()
ft::irc::reply_numerics ft::irc::channel::enter_user (ft::irc::user & user, const std::string & key)
References ft::irc::user::contains_invite(), ft::irc::user::load_mode(), and ft::irc::user::USER_MODE_OPERATOR.
get_key()
const std::string & ft::irc::channel::get_key () const throw ()
get_limit()
std::size_t ft::irc::channel::get_limit () const throw ()
get_mode()
bool ft::irc::channel::get_mode (channel_mode index) const throw ()
get_name()
const std::string & ft::irc::channel::get_name () const throw ()
get_topic()
const std::string & ft::irc::channel::get_topic () const throw ()
is_banned()
bool ft::irc::channel::is_banned (const ft::irc::user & user) const
References ft::irc::user::get_hostname(), ft::irc::user::get_username(), ft::irc::user::load_nick(), ft::irc::string_utils::match_mask(), and ft::irc::string_utils::match_mask_ignore_case().
is_channel_operator()
bool ft::irc::channel::is_channel_operator (const ft::irc::user & user) const throw ()
is_channel_speaker()
bool ft::irc::channel::is_channel_speaker (const ft::irc::user & user) const throw ()
leave_user()
void ft::irc::channel::leave_user (const ft::irc::user & user)
References ft::irc::make_reply::create(), ft::irc::channel::member::mode, ft::irc::server::remove_channel(), and ft::irc::channel::member::user.
load_key()
std::string ft::irc::channel::load_key () const
load_limit()
std::size_t ft::irc::channel::load_limit () const throw ()
load_mode()
bool ft::irc::channel::load_mode (channel_mode index) const throw ()
load_topic()
std::string ft::irc::channel::load_topic () const
make_list_packet()
ft::irc::message ft::irc::channel::make_list_packet (bool force) const
References ft::irc::make_reply::list(), and ft::irc::user::USER_MODE_INVISIBLE.
make_mode_string()
std::string ft::irc::channel::make_mode_string (std::string * param)
modify_member_mode()
void ft::irc::channel::modify_member_mode (const std::string & nick, member::member_mode index, bool value) throw ()
References ft::irc::string_utils::is_same().
operator=()
channel& ft::irc::channel::operator= (const channel &) private
send_ban_list()
void ft::irc::channel::send_ban_list (const ft::irc::user & user) const
References ft::irc::make_reply::ban_list(), ft::irc::make_reply::end_of_ban_list(), and ft::irc::user::send_message().
send_names()
void ft::irc::channel::send_names (const ft::irc::user & user) const
References ft::irc::make_reply::end_of_names(), ft::irc::user::is_channel_member(), ft::irc::member_info::is_chanop, ft::irc::member_info::is_chanspk, ft::irc::user::load_mode(), ft::irc::make_reply::name_reply(), ft::irc::member_info::nickname, ft::irc::user::send_message(), ft::irc::user::USER_MODE_INVISIBLE, and ft::irc::user::USER_MODE_OPERATOR.
set_key()
void ft::irc::channel::set_key (const std::string & key)
set_limit()
void ft::irc::channel::set_limit (std::size_t limit) throw ()
set_mode()
void ft::irc::channel::set_mode (channel_mode index, bool value) throw ()
set_topic()
void ft::irc::channel::set_topic (const std::string & topic)
store_key()
void ft::irc::channel::store_key (const std::string & key)
store_limit()
void ft::irc::channel::store_limit (std::size_t limit) throw ()
store_mode()
void ft::irc::channel::store_mode (channel_mode index, bool value) throw ()
store_topic()
void ft::irc::channel::store_topic (const std::string & topic)
unban()
void ft::irc::channel::unban (const std::string & mask)
References ft::irc::string_utils::is_same(), ft::irc::string_utils::pick_host(), ft::irc::string_utils::pick_nick(), and ft::irc::string_utils::pick_username().
Member Data Documentation
bans
ban_list ft::irc::channel::bans private
invalidated
bool ft::irc::channel::invalidated private
key
std::string ft::irc::channel::key private
limit
std::size_t ft::irc::channel::limit private
lock
ft::readwrite_lock ft::irc::channel::lock mutable private
members
member_list ft::irc::channel::members private
mode
std::bitset<NUMBEROF_CHANNEL_MODE> ft::irc::channel::mode private
name
std::string ft::irc::channel::name private
server
ft::irc::server& ft::irc::channel::server private
topic
std::string ft::irc::channel::topic private
The documentation for this class was generated from the following files:
channel.hpp
channel.cpp