ft_irc: ft::irc::processor_part Class Reference
ft::irc::processor_part Class Reference
#include <processor_channel.hpp>
Public Member Functions
std::size_t get_min_params () const throw ()
void execute (ft::irc::user &user, const ft::irc::message &message) const
Public Member Functions inherited from ft::irc::processor_base
virtual ~processor_base ()
virtual std::size_t get_max_params () const throw ()
virtual bool is_registered_only () const throw ()
virtual bool is_operator_only () const throw ()
Member Function Documentation
execute()
void ft::irc::processor_part::execute (ft::irc::user & user, const ft::irc::message & message) const inline virtual
Implements ft::irc::processor_base.
References ft::irc::channel::broadcast(), ft::irc::server::find_channel(), ft::irc::user::get_server(), ft::irc::user::is_channel_member(), ft::irc::channel::leave_user(), ft::irc::make_error::no_such_channel(), ft::irc::make_error::not_on_channel(), ft::irc::user::part_channel(), ft::irc::make_reply::replicate(), ft::irc::user::send_message(), and ft::irc::message::split().
get_min_params()
std::size_t ft::irc::processor_part::get_min_params () const throw () inline virtual
Reimplemented from ft::irc::processor_base.
The documentation for this class was generated from the following file:
processor_channel.hpp