ft_irc: ft::irc::make_reply Struct Reference
ft::irc::make_reply Struct Reference
#include <reply.hpp>
Static Public Member Functions
static ft::irc::message create (const std::string &command)
static ft::irc::message replicate (const ft::irc::message &message)
static ft::irc::message none ()
static ft::irc::message user_host (const std::vector< person_info > &found_person_list)
static ft::irc::message ison (const std::vector< std::string > &nickname_list)
static ft::irc::message away (param_t nickname, param_t msg)
static ft::irc::message unaway ()
static ft::irc::message now_away ()
static ft::irc::message whois_user (param_t nickname, param_t username, param_t host, param_t info)
static ft::irc::message whois_server (param_t nickname, param_t server_name, param_t info)
static ft::irc::message whois_operator (param_t nickname)
static ft::irc::message whois_idle (param_t nickname, long idle_time_second)
static ft::irc::message end_of_whois (param_t nickname)
static ft::irc::message whois_channels (param_t nickname, const std::vector< channel_info > &channel_list)
static ft::irc::message whowas_user (param_t nickname, param_t username, param_t host, param_t info)
static ft::irc::message end_of_whowas (param_t nickname)
static ft::irc::message list_start ()
static ft::irc::message list (param_t channel_name, std::size_t visible_count, param_t channel_topic)
static ft::irc::message list_end ()
static ft::irc::message channel_mode_is (param_t channel_name, param_t channel_mode, param_t mode_param)
static ft::irc::message no_topic (param_t channel_name)
static ft::irc::message topic (param_t channel_name, param_t channel_topic)
static ft::irc::message inviting (param_t channel_name, param_t nickname)
static ft::irc::message summoning (param_t username)
static ft::irc::message version (param_t version, int debug_level, param_t server_name, param_t comments)
static ft::irc::message who_reply (param_t channel_name, param_t username, param_t host, param_t server_name, param_t nickname, bool is_away, bool is_operator, bool is_chanop, bool is_chanspk, std::size_t hop_count, param_t info)
static ft::irc::message end_of_who (param_t name)
static ft::irc::message name_reply (bool is_secret_channel, bool is_private_channel, param_t channel_name, const std::vector< member_info > &user_list)
static ft::irc::message end_of_names (param_t channel_name)
static ft::irc::message links (param_t mask, param_t server_name, std::size_t hop_count, param_t info)
static ft::irc::message end_of_links (param_t mask)
static ft::irc::message ban_list (param_t channel_name, param_t ban_name, param_t ban_username, param_t ban_host)
static ft::irc::message end_of_ban_list (param_t channel_name)
static ft::irc::message info (param_t info)
static ft::irc::message end_of_info ()
static ft::irc::message motd_start (param_t server_name)
static ft::irc::message motd (param_t text)
static ft::irc::message end_of_motd ()
static ft::irc::message now_operator ()
static ft::irc::message rehashing (param_t config_filename)
static ft::irc::message time (param_t server_name, param_t local_time_str)
static ft::irc::message users_start ()
static ft::irc::message users (param_t utmp_name, param_t utmp_line, param_t utmp_host)
static ft::irc::message end_of_users ()
static ft::irc::message no_users ()
static ft::irc::message trace_link (param_t version, int debug_level, param_t destination_server_name, param_t next_server_name)
static ft::irc::message trace_connecting (int client_class, param_t client_name)
static ft::irc::message trace_handshake (int client_class, param_t client_name)
static ft::irc::message trace_unknown (int client_class, param_t client_name)
static ft::irc::message trace_operator (int client_class, param_t client_name)
static ft::irc::message trace_user (int client_class, param_t client_name)
static ft::irc::message trace_server (int client_class, std::size_t server_count, std::size_t client_count, param_t client_name, param_t by, param_t username, param_t host)
static ft::irc::message trace_new_type (param_t new_type, param_t client_name)
static ft::irc::message trace_log (param_t log_filename, int debug_level)
static ft::irc::message stats_link_info (param_t linkname, int sendq, param_t sent_messages, int sent_bytes, param_t received_messages, int received_bytes, int time_open)
static ft::irc::message stats_commands (param_t command, unsigned count)
static ft::irc::message stats_c_line (param_t host, param_t pass, param_t name, int port, int conf_class)
static ft::irc::message stats_n_line (param_t host, param_t pass, param_t name, int port, int conf_class)
static ft::irc::message stats_i_line (param_t host, param_t pass, param_t name, int port, int conf_class)
static ft::irc::message stats_k_line (param_t host, param_t pass, param_t name, int port, int conf_class)
static ft::irc::message stats_y_line (int class_class, int ping_freq, int conn_freq, int max_sendq)
static ft::irc::message end_of_stats (char stats_letter)
static ft::irc::message stats_l_line (param_t host, param_t pass, param_t name, int max_depth)
static ft::irc::message stats_uptime (int days, int hours, int minutes, int seconds)
static ft::irc::message stats_o_line (param_t host, param_t pass, param_t name)
static ft::irc::message stats_h_line (param_t host, param_t pass, param_t name)
static ft::irc::message user_mode_is (param_t user_mode)
static ft::irc::message luser_client (std::size_t user_count, std::size_t invisible_count, std::size_t server_count)
static ft::irc::message luser_operator (std::size_t op_count)
static ft::irc::message luser_unknown (std::size_t unknown_count)
static ft::irc::message luser_channels (std::size_t channel_count)
static ft::irc::message luser_me (std::size_t client_count, std::size_t server_count)
static ft::irc::message admin_me (param_t server_name)
static ft::irc::message admin_loc1 (param_t location)
static ft::irc::message admin_loc2 (param_t location_detail)
static ft::irc::message admin_email (param_t email_address)
Static Public Member Functions inherited from ft::irc::make_reply_base
static void set_server_name (const std::string &str)
static void set_user_name (const std::string &str)
static void set_user_nick (const std::string &str)
Additional Inherited Members
Public Types inherited from ft::irc::make_reply_base
typedef const std::string & param_t
Static Public Attributes inherited from ft::irc::make_reply_base
static ft::thread_specific_ptr< std::string > my_server_name
static ft::thread_specific_ptr< std::string > my_user_name
static ft::thread_specific_ptr< std::string > my_user_nick
Member Function Documentation
admin_email()
static ft::irc::message ft::irc::make_reply::admin_email (param_t email_address) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
admin_loc1()
static ft::irc::message ft::irc::make_reply::admin_loc1 (param_t location) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
admin_loc2()
static ft::irc::message ft::irc::make_reply::admin_loc2 (param_t location_detail) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
admin_me()
static ft::irc::message ft::irc::make_reply::admin_me (param_t server_name) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
away()
static ft::irc::message ft::irc::make_reply::away (param_t nickname, param_t msg) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
ban_list()
static ft::irc::message ft::irc::make_reply::ban_list (param_t channel_name, param_t ban_name, param_t ban_username, param_t ban_host) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
channel_mode_is()
static ft::irc::message ft::irc::make_reply::channel_mode_is (param_t channel_name, param_t channel_mode, param_t mode_param) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
create()
static ft::irc::message ft::irc::make_reply::create (const std::string & command) inline static
References ft::irc::make_reply_base::my_server_name.
end_of_ban_list()
static ft::irc::message ft::irc::make_reply::end_of_ban_list (param_t channel_name) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
end_of_info()
static ft::irc::message ft::irc::make_reply::end_of_info () inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
end_of_links()
static ft::irc::message ft::irc::make_reply::end_of_links (param_t mask) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
end_of_motd()
static ft::irc::message ft::irc::make_reply::end_of_motd () inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
end_of_names()
static ft::irc::message ft::irc::make_reply::end_of_names (param_t channel_name) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
end_of_stats()
static ft::irc::message ft::irc::make_reply::end_of_stats (char stats_letter) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
end_of_users()
static ft::irc::message ft::irc::make_reply::end_of_users () inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
end_of_who()
static ft::irc::message ft::irc::make_reply::end_of_who (param_t name) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
end_of_whois()
static ft::irc::message ft::irc::make_reply::end_of_whois (param_t nickname) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
end_of_whowas()
static ft::irc::message ft::irc::make_reply::end_of_whowas (param_t nickname) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
info()
static ft::irc::message ft::irc::make_reply::info (param_t info) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
inviting()
static ft::irc::message ft::irc::make_reply::inviting (param_t channel_name, param_t nickname) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
ison()
static ft::irc::message ft::irc::make_reply::ison (const std::vector< std::string > & nickname_list) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
links()
static ft::irc::message ft::irc::make_reply::links (param_t mask, param_t server_name, std::size_t hop_count, param_t info) inline static
References info(), ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
list()
static ft::irc::message ft::irc::make_reply::list (param_t channel_name, std::size_t visible_count, param_t channel_topic) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
list_end()
static ft::irc::message ft::irc::make_reply::list_end () inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
list_start()
static ft::irc::message ft::irc::make_reply::list_start () inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
luser_channels()
static ft::irc::message ft::irc::make_reply::luser_channels (std::size_t channel_count) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
luser_client()
static ft::irc::message ft::irc::make_reply::luser_client (std::size_t user_count, std::size_t invisible_count, std::size_t server_count) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
luser_me()
static ft::irc::message ft::irc::make_reply::luser_me (std::size_t client_count, std::size_t server_count) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
luser_operator()
static ft::irc::message ft::irc::make_reply::luser_operator (std::size_t op_count) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
luser_unknown()
static ft::irc::message ft::irc::make_reply::luser_unknown (std::size_t unknown_count) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
motd()
static ft::irc::message ft::irc::make_reply::motd (param_t text) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
motd_start()
static ft::irc::message ft::irc::make_reply::motd_start (param_t server_name) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
name_reply()
static ft::irc::message ft::irc::make_reply::name_reply (bool is_secret_channel, bool is_private_channel, param_t channel_name, const std::vector< member_info > & user_list) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
no_topic()
static ft::irc::message ft::irc::make_reply::no_topic (param_t channel_name) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
no_users()
static ft::irc::message ft::irc::make_reply::no_users () inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
none()
static ft::irc::message ft::irc::make_reply::none () inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
now_away()
static ft::irc::message ft::irc::make_reply::now_away () inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
now_operator()
static ft::irc::message ft::irc::make_reply::now_operator () inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
rehashing()
static ft::irc::message ft::irc::make_reply::rehashing (param_t config_filename) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
replicate()
static ft::irc::message ft::irc::make_reply::replicate (const ft::irc::message & message) inline static
References ft::irc::make_reply_base::my_user_name.
stats_c_line()
static ft::irc::message ft::irc::make_reply::stats_c_line (param_t host, param_t pass, param_t name, int port, int conf_class) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
stats_commands()
static ft::irc::message ft::irc::make_reply::stats_commands (param_t command, unsigned count) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
stats_h_line()
static ft::irc::message ft::irc::make_reply::stats_h_line (param_t host, param_t pass, param_t name) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
stats_i_line()
static ft::irc::message ft::irc::make_reply::stats_i_line (param_t host, param_t pass, param_t name, int port, int conf_class) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
stats_k_line()
static ft::irc::message ft::irc::make_reply::stats_k_line (param_t host, param_t pass, param_t name, int port, int conf_class) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
stats_l_line()
static ft::irc::message ft::irc::make_reply::stats_l_line (param_t host, param_t pass, param_t name, int max_depth) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
stats_link_info()
static ft::irc::message ft::irc::make_reply::stats_link_info (param_t linkname, int sendq, param_t sent_messages, int sent_bytes, param_t received_messages, int received_bytes, int time_open) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
stats_n_line()
static ft::irc::message ft::irc::make_reply::stats_n_line (param_t host, param_t pass, param_t name, int port, int conf_class) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
stats_o_line()
static ft::irc::message ft::irc::make_reply::stats_o_line (param_t host, param_t pass, param_t name) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
stats_uptime()
static ft::irc::message ft::irc::make_reply::stats_uptime (int days, int hours, int minutes, int seconds) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
stats_y_line()
static ft::irc::message ft::irc::make_reply::stats_y_line (int class_class, int ping_freq, int conn_freq, int max_sendq) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
summoning()
static ft::irc::message ft::irc::make_reply::summoning (param_t username) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
time()
static ft::irc::message ft::irc::make_reply::time (param_t server_name, param_t local_time_str) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
topic()
static ft::irc::message ft::irc::make_reply::topic (param_t channel_name, param_t channel_topic) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
trace_connecting()
static ft::irc::message ft::irc::make_reply::trace_connecting (int client_class, param_t client_name) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
trace_handshake()
static ft::irc::message ft::irc::make_reply::trace_handshake (int client_class, param_t client_name) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
trace_link()
static ft::irc::message ft::irc::make_reply::trace_link (param_t version, int debug_level, param_t destination_server_name, param_t next_server_name) inline static
References ft::irc::make_reply_base::my_server_name, ft::irc::make_reply_base::my_user_nick, and version().
trace_log()
static ft::irc::message ft::irc::make_reply::trace_log (param_t log_filename, int debug_level) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
trace_new_type()
static ft::irc::message ft::irc::make_reply::trace_new_type (param_t new_type, param_t client_name) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
trace_operator()
static ft::irc::message ft::irc::make_reply::trace_operator (int client_class, param_t client_name) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
trace_server()
static ft::irc::message ft::irc::make_reply::trace_server (int client_class, std::size_t server_count, std::size_t client_count, param_t client_name, param_t by, param_t username, param_t host) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
trace_unknown()
static ft::irc::message ft::irc::make_reply::trace_unknown (int client_class, param_t client_name) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
trace_user()
static ft::irc::message ft::irc::make_reply::trace_user (int client_class, param_t client_name) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
unaway()
static ft::irc::message ft::irc::make_reply::unaway () inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
user_host()
static ft::irc::message ft::irc::make_reply::user_host (const std::vector< person_info > & found_person_list) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
user_mode_is()
static ft::irc::message ft::irc::make_reply::user_mode_is (param_t user_mode) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
users()
static ft::irc::message ft::irc::make_reply::users (param_t utmp_name, param_t utmp_line, param_t utmp_host) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
users_start()
static ft::irc::message ft::irc::make_reply::users_start () inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
version()
static ft::irc::message ft::irc::make_reply::version (param_t version, int debug_level, param_t server_name, param_t comments) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
who_reply()
static ft::irc::message ft::irc::make_reply::who_reply (param_t channel_name, param_t username, param_t host, param_t server_name, param_t nickname, bool is_away, bool is_operator, bool is_chanop, bool is_chanspk, std::size_t hop_count, param_t info) inline static
References info(), ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
whois_channels()
static ft::irc::message ft::irc::make_reply::whois_channels (param_t nickname, const std::vector< channel_info > & channel_list) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
whois_idle()
static ft::irc::message ft::irc::make_reply::whois_idle (param_t nickname, long idle_time_second) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
whois_operator()
static ft::irc::message ft::irc::make_reply::whois_operator (param_t nickname) inline static
References ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
whois_server()
static ft::irc::message ft::irc::make_reply::whois_server (param_t nickname, param_t server_name, param_t info) inline static
References info(), ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
whois_user()
static ft::irc::message ft::irc::make_reply::whois_user (param_t nickname, param_t username, param_t host, param_t info) inline static
References info(), ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
whowas_user()
static ft::irc::message ft::irc::make_reply::whowas_user (param_t nickname, param_t username, param_t host, param_t info) inline static
References info(), ft::irc::make_reply_base::my_server_name, and ft::irc::make_reply_base::my_user_nick.
The documentation for this struct was generated from the following file:
reply.hpp